### ISSUE TITLE
Password of '123B' was not cracked by default query.

### ISSUE THREAD

**Issue by rhodesj971** [mufeedvh/pdfrip#19]
Hi - I have a PDF secured with the password '123B'. Using the query:
`pdfrip -f file.pdf -n 12 default-query --max-length 4 --min-length 4`

I'd expect the tool to find the password no problem - but it doesn't. If I reverse the password to B123, it finds it. I assumed the default query would run all permutations of a-zA-Z0-9 but it seems not?

Thanks!

**Comment by mufeedvh** [comment]
Just fixed this! Thank you for opening this issue!

![Screenshot from 2024-01-09 18-55-49](https://github.com/mufeedvh/pdfrip/assets/26198477/440512ef-f1fe-49ef-a10a-f4bf099cb322)
