### ISSUE TITLE
Colors not working on Windows 10

### ISSUE THREAD

**Issue by princessmortix** [mufeedvh/pdfrip#2]
Some colors works, others doesn't, here a screenshot of it:

![image](https://user-images.githubusercontent.com/47502554/179123038-91fb9ea4-8253-4d9b-ad29-9a98890a8712.png)

I've tested both with powershell and cmd on Windows 10 Pro 21H1.

User name hidden due of privacy reasons.

**Comment by mufeedvh** [comment]
Fixed in https://github.com/mufeedvh/pdfrip/commit/ed76bb2f190ddee709e89e0341aa41ef2a451e30. Thank you for opening this issue!
