### ISSUE TITLE
Digital password didn't find by range but by default-query

### ISSUE THREAD

**Issue by LiShaoyu5** [mufeedvh/pdfrip#29]
At first, I tried with the command
`pdfrip.exe -f x.pdf range 000000 999999`
and it failed. Then I tried
`pdfrip.exe -f x.pdf default-query --max-length 6 --min-length 6`
and it finds the password 001631.
![image](https://github.com/mufeedvh/pdfrip/assets/37066594/89c3075a-93f6-49c2-b9dd-fa0fea61db95)

**Comment by Windows200000** [comment]
Maybe you could try reading [README.md](https://github.com/mufeedvh/pdfrip#:~:text=Enable%20preceding%20zeros%20for%20custom%20queries%3A%20(which%20would%20make%20%7B10%2D5000%7D%20to%20%7B0010%2D5000%7D%20matching%20the%20end%20range%27s%20digits)).

**Comment by LiShaoyu5** [comment]
> Maybe you could try reading [README.md](https://github.com/mufeedvh/pdfrip#:~:text=Enable%20preceding%20zeros%20for%20custom%20queries%3A%20(which%20would%20make%20%7B10%2D5000%7D%20to%20%7B0010%2D5000%7D%20matching%20the%20end%20range%27s%20digits)).

very helpful, thank you
