### ISSUE TITLE
can't crack the aes256 ones

### ISSUE THREAD

**Issue by canyazbahar** [mufeedvh/pdfrip#3]
I can't crack the pdf i created. and password is 123456.
it can only crack acrobat 6 and 7 versions. not X versions.

![settings](https://user-images.githubusercontent.com/65427320/214142783-9d920487-4df2-4f74-9cf0-9db4c26bf44b.png)

**Comment by mufeedvh** [comment]
This has been implemented in v2.0.0. Thanks for opening this issue! :raised_hands:

**Comment by dominik-b13** [comment]
Im using 2.0.1 and this seems still like its not working with aes256 documents. i tested it with the correct password in a wordlist and it does not find the password

**Comment by Gugabf** [comment]
I think it still doesn't work (v2.0.1).
I tested it now with a simple numeric password and it only discovers the password if it is saved in versions 6.0 or 7.0, like @canyazbahar said when opened this issue.
It doesn't work in version "X" ("Failed to crack file..." message).
